server.port=${PORT:8080}
server.address=0.0.0.0
spring.profiles.active=dev

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false





## ===========================
## Server
## ===========================
#server.port=${PORT:8080}
#server.address=0.0.0.0
#
## ===========================
## H2 Database Configuration
## ===========================
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## ===========================
## JPA / Hibernate
## ===========================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true
#
## ===========================
## Thymeleaf / Dev
## ===========================
#spring.thymeleaf.cache=false
#spring.web.resources.cache.period=0
#spring.web.resources.chain.cache=false